# Generated by Django 5.1.3 on 2025-02-21 14:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_whishlistitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whishlistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
