# Generated by Django 5.1.3 on 2025-01-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_coupons_details_coupons_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='details',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
