# Generated by Django 5.1.3 on 2025-01-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupons_details_alter_coupons_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
