# Generated by Django 5.1.3 on 2024-12-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Mohammed Shamil M', max_length=100),
            preserve_default=False,
        ),
    ]
