# Generated by Django 5.1.3 on 2024-12-17 05:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_address_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='address',
            new_name='user_address',
        ),
    ]
