# Generated by Django 5.1.3 on 2024-12-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartandcheckout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='Cart',
        ),
    ]
