# Generated by Django 5.1.3 on 2024-12-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartandcheckout', '0002_rename_cart_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(default='k', upload_to='cart_images/'),
            preserve_default=False,
        ),
    ]
