# Generated by Django 5.1.3 on 2025-01-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartandcheckout', '0003_cartitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='item_total',
        ),
    ]
