# Generated by Django 5.1.3 on 2025-01-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
