# Generated by Django 5.1.3 on 2025-01-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.shipping_address'),
        ),
    ]
