# Generated by Django 5.1.3 on 2025-01-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failure', 'Failure')], default='Order Pending', max_length=50),
        ),
    ]
