# Generated by Django 5.1.3 on 2025-01-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_items_product_alter_order_items_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='variant',
            field=models.CharField(max_length=50),
        ),
    ]
