# Generated by Django 5.1.3 on 2025-01-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orders_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='status',
            field=models.CharField(choices=[('Order Pending', 'Order Pending'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Requested Return', 'Requested Return'), ('Approve Return', 'Approve Return'), ('Returned', 'Returned')], default='Order Pending', max_length=20),
        ),
    ]
