# Generated by Django 5.1.3 on 2025-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_items_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Requested Return', 'Requested Return'), ('Approve Return', 'Approve Return'), ('Returned', 'Returned')], default='Order Pending', max_length=20),
        ),
    ]
