# Generated by Django 5.1.3 on 2025-02-21 15:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_items_price_alter_orders_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
