# Generated by Django 5.1.3 on 2024-12-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='name',
            new_name='RAM',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='value',
            new_name='color',
        ),
        migrations.AddField(
            model_name='variant',
            name='storage',
            field=models.CharField(default='128GB', max_length=100),
            preserve_default=False,
        ),
    ]
