# Generated by Django 5.1.3 on 2024-12-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_name_variant_ram_rename_value_variant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
