# Generated by Django 5.1.3 on 2025-01-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_variant_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='offer',
            field=models.IntegerField(null=True),
        ),
    ]
