# Generated by Django 5.1.3 on 2025-01-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_variant_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
