# Generated by Django 5.1.3 on 2025-01-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_variant_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='offer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
