# Generated by Django 5.1.3 on 2025-02-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_variant_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=10), max_digits=10),
        ),
    ]
