# Generated by Django 5.1.3 on 2025-02-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_variant_final_price_alter_variant_ram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='final_price',
        ),
    ]
