# Generated by Django 5.1.3 on 2025-02-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_variant_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
