# Generated by Django 5.1.3 on 2025-02-21 15:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_variant_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
