# Generated by Django 5.1.3 on 2025-02-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_variant_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='RAM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='storage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
