# Generated by Django 5.1.3 on 2025-02-21 15:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_variant_final_price_alter_variant_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
